config/routes.rb
Rails.application.routes.draw do
  root "transactions#index"

  resources :categories
  resources :transactions
  resources :reports, only: [:index]
  
  get 'reports', to: 'reports#index'
  get 'reports/transaction_report', to: 'reports#transaction_report'
  get 'reports/d_b_d_report', to: 'reports#d_b_d_report'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: {message: "Поле не може бути пустим"}, length: {maximum: 20, message:"Довжинна повинна бути менше 20 симовлів"}
    validates :description, presence: {message: "Поле не може бути пустим"}, length: {minimum:10, maximum:50, message:"Довжина повинна бути між 10 та 50 символами"}

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "id_value", "name", "updated_at"]
    end
end

app/models/transaction.rb
class Transaction < ApplicationRecord

    with_options presence: {message:"Поле не може бути пустим"} do
       validates :amount, numericality:{only_integer: true, message: "В дамому полі можуть бути тільки цифри"}
       validates :description, length: {minimum:5, maximum:50, message:"Довжина повинна бути між 5 та 50 символами"}
    end 
    validates :operation_type, inclusion: {in: %w(Витрата Прихід), message:"Виберіть тип операції"}
    validates :category, inclusion: { in: ->(record){ Category.select(:name).distinct.pluck(:name)}, message:"Виберіть категорію"}

    def self.ransackable_attributes(auth_object = nil)
        ["amount", "category", "created_at", "description", "id", "id_value", "operation_type", "updated_at"]
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


    def index
        @q = Category.ransack(params[:q])
        @categories = @q.result(distinct: true)
    end

    def new
        @category = Category.new()
    end

    def show
        @category = Category.find(params[:id])
    end

    def create
        @category = Category.new(category_params)

        if @category.save
            redirect_to categories_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])

        if @category.update(category_params)
            redirect_to categories_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy

        redirect_to categories_path
    end
    
    private

    def category_params
        params.require(:category).permit(:name, :description,:name_cont)
    end
    

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    
    before_action :form_data, only: [:index, :transaction_report, :d_b_d_report]

    def index
    end
  
    def transaction_report
        @transactions_expenses_revenues = @transactions.group_by { |t| t.category }.transform_values { |transactions| transactions.sum(&:amount) }
    end
  
    def d_b_d_report
        @transactions_by_date = @transactions.group_by { |t| t.updated_at.to_date }.transform_values { |transactions| transactions.sum(&:amount) }
    end

    private

    def form_data
        @categories = Category.select(:name).distinct.pluck(:name)
        @start_date = params[:start_date].present? ? Date.parse(params[:start_date]) : 1.month.ago.to_date
        @end_date = params[:end_date].present? ? Date.parse(params[:end_date]) : Date.today
        @category = params[:category]
        @operation_type = params[:operation_type]
        @transactions = Transaction.where(updated_at: @start_date.beginning_of_day..@end_date.end_of_day)
        @transactions = @transactions.where(category: @category) if @category.present?
        @transactions = @transactions.where(operation_type: @operation_type) if @operation_type.present?
    end
    
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

    def index
        @q = Transaction.ransack(params[:q])
        @transactions = @q.result(distinct: true).page(params[:page])
    end

    def show
        @transaction = Transaction.find(params[:id])
    end

    def new
        @transaction = Transaction.new
        @categories = Category.select(:name).distinct.pluck(:name)
    end

    def create
        @transaction = Transaction.new(transaction_params)

        if @transaction.save
            redirect_to transactions_path
        else
            @categories = Category.select(:name).distinct.pluck(:name)
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @transaction = Transaction.find(params[:id])
        @categories = Category.select(:name).distinct.pluck(:name)
    end

    def update
        @transaction = Transaction.find(params[:id])

        if @transaction.update(transaction_params)
            redirect_to transactions_path
        else
            @categories = Category.select(:name).distinct.pluck(:name)
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @transaction = Transaction.find(params[:id])
        @transaction.destroy

        redirect_to transaction_path
    end

    
    
    private

    def transaction_params
        params.require(:transaction).permit(:category, :operation_type, :amount, :description, :updated_at)
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_form.html.erb
<div class="form-container">
    <%=form_with model: @category do |f| %>

        <%= f.label "Назва"%>
        <%= f.text_field :name%>
        <%if @category.errors[:name].any?%>
            <div class="error"><%= @category.errors[:name].first%></div>
        <%end%>

        <%= f.label "Опис"%>
        <%= f.text_field :description%>
        <%if @category.errors[:description].any?%>
            <div class="error"><%= @category.errors[:description].first%></div>
        <%end%>

       <div class="form__buttons">
            <% if @category.new_record? %>
                <%= f.button "Створити", type: "submit", class: "button" %>
            <% else %>
                <%= f.button "Оновити", type: "submit", class: "button" %>
            <% end %>
            <%= f.button "Скасувати", type: "reset", class: "button" %>
        </div>

    <%end%>
</div>

app/views/categories/_search_form_for.html.erb
<%= search_form_for @q do |f| %>

            
    <%= f.label :name_cont %>
    <%= f.search_field :name_cont %>
            
    <%=f.submit%>
<%end%>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<div class="categories">
    <div class="content">

        <h1>Категорії</h1>
        <div class="search-form">
            <%= search_form_for @q do |f| %>
                <%= f.search_field :name_cont, class:"search-field", placeholder:"Введіть перші літери назви категорії" %>
                            
                <%=f.button "Пошук", type: "submin", class:"search-button"%>
            <%end%>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>Назва</th>
                    <th>Опис</th>
                    <th>Управління</th>
                </tr>
            </thead>

            <tbody> 
                <%@categories.each do |element|%>
                    <tr>
                        <th><%= element.name%></th>
                        <th><%= element.description%></th>

                        <th>
                            <%=link_to "Змінити", edit_category_path(element)%>
                            <%=link_to "Видалити", category_path(element), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                            }%>                      
                        </th>
                    </tr>
                <%end%>
            </tbody>
        </table>
        <button class="button"><%=link_to "Додати нову категорію", new_category_path %></button>
    </div>
</div>

app/views/categories/new.html.erb
<div class="content">
    <%=render "form"%>
</div>

app/views/categories/show.html.erb
<div class="content">
    <h1>Категорія <%=@category.name%></h1>

    <h3>Опис категорії: <%=@category.description%></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  
  </head>

  <body>

    <header>
      <div class="header__content">
        <menu>
          <ul>
            <li> <%=link_to "Категорії", categories_path%> </li>
            <li> <%=link_to "Транзакції", transactions_path%> </li>
            <li> <%=link_to "Звіти", reports_path%> </li>
          </ul>
        </menu>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/reports/d_b_d_report.html.erb
<div class="content">
    <h1>Діагрма за період по датам</h1>
    
    <%= line_chart @transactions_by_date %>
</div>

app/views/reports/index.html.erb
<div class="form-container">
  <%= form_with(url: reports_path, method: :get) do |f| %>
    <%= f.label "Початкова дата" %>
    <%= f.date_field :start_date, value: @start_date %>

    <%= f.label "Кінцева дата" %>
    <%= f.date_field :end_date, value: @end_date %>

    <%= f.label "Тип операції" %>
    <%= f.select :operation_type, ["Витрата", "Прихід"]%>

    <%= f.label "Категорія" %>
    <%= f.select :category, @categories, prompt: "Виберіть категорію"%>
    
    <div class="form__buttons">
      <%= f.button "Створити звіт", type: "submit", formaction: reports_transaction_report_path, class: "button" %>
      <%= f.button "Графік по датах", type: "submit", formaction: reports_d_b_d_report_path,  class: "button"  %>
      <%= f.button "Скинути", type: "reset",  class: "button"  %>
    </div>
  <% end %>
</div>

app/views/reports/transaction_report.html.erb
<div class="content">
    <h1>Звіт за період <%=@start_date%> - <%=@end_date%></h1>
    <h3><%=@operation_type %></h3>
    <div class="table-report" style="width:400px" >
        <table>
            <thead>
                <tr>
                    <th>Категорія</th>
                    <th>Сума</th>
                </tr>
            </thead>

            <tbody>
                <%@transactions_expenses_revenues.each do |key, value|%>
                <tr>
                    <th><%=key%></th>
                    <th><%=value%></th>
                </tr>
                <%end%>
                <tr style="background-color:rgb(138, 216, 20)">
                    <th>Сума</th>
                    <th><%=@transactions_expenses_revenues.values.sum%> грн</th>
                </tr>
            </tbody>
        </table>
    </div>

    <%= pie_chart @transactions_expenses_revenues %>


</div>

app/views/transactions/_form.html.erb
<div class="form-container">
    <%=form_with model: @transaction do |f|%>

    <%=f.label "Категорія"%>
    <%=f.select :category, @categories, prompt: "Виберіть категорію" %>
    <%if @transaction.errors[:category].any?%>
        <div class="error"><%=@transaction.errors[:category].first%></div>
    <%end%>

    <%=f.label "Тип операції"%>
    <%=f.select :operation_type, ["Витрата", "Прихід"], prompt: "Виберіть тип операції"%>
    <%if @transaction.errors[:operation_type].any?%>
        <div class="error"><%= @transaction.errors[:operation_type].first%></div>
    <%end%>

    <%=f.label "Ціна"%>
    <%=f.text_field :amount%>
    <%if @transaction.errors[:amount].any?%>
        <div class="error"><%=@transaction.errors[:amount].first%></div>
    <%end%>

    <%=f.label "Опис"%>
    <%=f.text_field :description%>
    <%if @transaction.errors[:description].any?%>
        <div class="error"><%=@transaction.errors[:description].first%></div>
    <%end%>

    <%=f.label "Дата"%>
    <%=f.date_field :updated_at%>
    

    <div class="form__buttons">
        <% if @transaction.new_record? %>
            <%= f.button "Створити", type: "submit", class: "button" %>
        <% else %>
            <%= f.button "Оновити", type: "submit", class: "button" %>
        <% end %>
        <%= f.button "Скасувати", type: "reset", class: "button" %>
    </div>
<%end%>
</div>

app/views/transactions/edit.html.erb
<%=render "form" %>

app/views/transactions/index.html.erb
<div class="transactions">
  <div class="content">

  <h1>Транзакції</h1>
    <table>
      <thead>
        <tr>
          <th><%= sort_link(@q, :category, "Категорія", default_order: :desc) %></th>
          <th><%= sort_link(@q, :operation_type, "Тип операції", default_order: :desc) %></th>
          <th><%= sort_link(@q, :amount, "Сума", default_order: :desc) %></th>
          <th><%= sort_link(@q, :description, "Опис", default_order: :desc) %></th>
          <th><%= sort_link(@q, :updated_at, "Дата", default_order: :desc) %></th>
          <th>Управління</th>
        </tr>
      </thead>

      <tbody>
        <% @transactions.each do |element| %>
          <tr>
            <th><%= element.category %></th>
            <th><%= element.operation_type %></th>
            <th><%= element.amount %></th>
            <th><%= element.description %></th>
            <th><%= element.updated_at.strftime("%Y-%m-%d") %></th>
            <th>
              <%= link_to "Змінити", edit_transaction_path(element) %>
              <%= link_to "Видалити", transaction_path(element), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </th>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @transactions%>
    <button class="button"><%= link_to "Додати нову транзакцію", new_transaction_path %></button>

  
  </div>
</div>

app/views/transactions/new.html.erb
<%=render "form" %>

app/views/transactions/show.html.erb
<div class="content">
    <p><%=@transaction.category%></p>
    <p><%=@transaction.operation_type%></p>
    <p><%=@transaction.amount%></p>
    <p><%=@transaction.description%></p>
    <p><%=@transaction.updated_at%></p>
</div>